### ISSUE TITLE
Wrong dependencies

### ISSUE THREAD

**Issue by aroberge** [conda-forge/friendly-traceback-feedstock#89]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The dependencies listed in https://github.com/conda-forge/friendly-traceback-feedstock/blob/main/recipe/meta.yaml, namely
```
    - asttokens >=2.0.4
    - executing >=0.8.3
    - pure_eval >=0.2.1
    - python >=3.6
    - stack_data >=0.1.3
```
are incorrect for the latest version of this package.

The corrected ones should be as follows:
```
- asttokens >= 2.0.4
- executing >= 1.1.0
- pure_eval >= 0.2.1
- python >=3.6
- stack_data >= 0.5.1
- six >= 1.16
```

Following https://github.com/friendly-traceback/friendly-traceback/issues/153, I looked into what I could do to help maintain this, but I only have access to a Windows computer which does not appear to be supported from what I read on the scripts.

### Installed packages

```shell
Not applicable
```

### Environment info

```shell
Not applicable
```

**Comment by thewchan** [comment]
Thanks for checking @aroberge, I will make this change and push a new version asap

**Comment by thewchan** [comment]
And I can add you as a maintainer as well

**Comment by aroberge** [comment]
I don't mind at all being a maintainer, if it means that I can update the information. But I don't know how to "push" a new version if required - and I only have access to a Windows computer.

**Comment by thewchan** [comment]
You can do so by creating a fork on github, making the change there and, and submit a PR here from your fork. All can be done in the GH web interface.
